チャットのテスト
ta910/chat-space pull request #13
Opened 2017-02-05 15:45 UTC by ta910

# What
モデルとコントローラーのテスト
# Why
動作確認のため

2017-02-05 15:48 UTC, ta910 commented
![2017-02-06 0 47 51](https://cloud.githubusercontent.com/assets/21980655/22627407/ec105420-ec05-11e6-896b-bd38d7473220.png)

2017-02-05 15:48 UTC, ta910 commented
コントローラーのテストでエラーになってしまって対処法がわかりません、、、

2017-02-05 16:13 UTC, nkz-d requested changes

2017-02-05 16:13 UTC, nekoze1210 commented on spec/controllers/chats_controller_spec.rb
> +  let(:groups) { create(:group) }
groupと中身一緒になっているから、create_listにした方が良さそう

2017-02-05 16:13 UTC, nekoze1210 commented on spec/controllers/chats_controller_spec.rb
> +     chat = Chat.new(body: nil)
FactoryGirlのメソッド使って欲しいなぁ…　newだったらbuildでいけそう！

2017-02-05 16:13 UTC, nekoze1210 commented on spec/controllers/chats_controller_spec.rb
> +    let(:request) { post :create, group_id: group, message: attributes_for(:chat) }
これも使ってないから必要ないんじゃない？
あと、requestはrailsの予約語だ（ったはずだ）から変えたほうがいいかも

2017-02-05 16:13 UTC, nekoze1210 commented on spec/factories/chats.rb
> +    user_id               "1"
クォーテーション外してエラー起きた？

2017-02-05 16:23 UTC, ta910 commented on spec/controllers/chats_controller_spec.rb
> +     chat = Chat.new(body: nil)
使いました！

2017-02-05 16:23 UTC, ta910 commented on spec/controllers/chats_controller_spec.rb
> +    let(:request) { post :create, group_id: group, message: attributes_for(:chat) }
消します！

2017-02-05 16:23 UTC, ta910 commented on spec/controllers/chats_controller_spec.rb
> +  let(:groups) { create(:group) }
groups使ってないので消しました！

2017-02-05 16:26 UTC, ta910 commented on spec/factories/chats.rb
> +    user_id               "1"
文字列は外したらエラーでした、、

2017-02-05 16:27 UTC, ta910 commented
やはり３つのエラーが直らないです、、

2017-02-06 01:19 UTC, nekoze1210 commented
deviseのログイン処理って書いた？
あとはbinding.pryで一行ずつレコードが入ってるか確認するしか…

2017-02-06 06:11 UTC, ta910 commented
rspecのテストのgotがnilってことはなんらかの理由（ログインできてないとか）で情報をとりだせていないってことですか、、？

2017-02-06 06:24 UTC, ta910 commented
ログイン処理してもダメでメンブレしてます

2017-02-06 06:38 UTC, ta910 commented
![2017-02-06 15 37 57](https://cloud.githubusercontent.com/assets/21980655/22636952/4aa76d30-ec82-11e6-9658-07c4dfa307e6.png)

2017-02-06 06:38 UTC, ta910 commented
なおりました！

2017-02-06 07:13 UTC, nekoze1210 commented
LGTM

2017-02-06 07:14 UTC, merged