メッセージ送信機能の非同期通信化
ta910/chat-space pull request #14
Opened 2017-02-07 08:15 UTC by ta910

# What
メッセージの非同期通信化
# Why
非同期で通信できるようにするため

2017-02-07 08:39 UTC, ta910 commented
グループ内での最初のメッセージだけ非同期でなく普通に送れてしまう上、次からのメッセージはエラーになっちゃいます、、、

2017-02-07 08:44 UTC, ta910 commented
![2017-02-07 17 43 22](https://cloud.githubusercontent.com/assets/21980655/22683784/00c05bf6-ed5d-11e6-886c-3a5b312d8b41.png)

2017-02-08 01:12 UTC, nekoze1210 commented
> 非同期でなく普通に送れてしまう

これはきっとturbolinksでjsが動いていない可能性があるかな

それ以降は単純にjsの書き方の問題でエラーが返されてるかんじかな？

2017-02-08 01:49 UTC, nkz-d requested changes

2017-02-08 01:49 UTC, nekoze1210 commented on app/assets/javascripts/chat.js
> +    var html = '<li class="chat">' + '<div class="chat_content">' + '<h3>' + chat.user.name + '</h3>' + '<h5>' + chat.created_at + '</h5>' + '<h4>' + chat.body + '</h4>' + '</div>' + '</li>'
レコードの引っ張り方が間違ってるね！
railsみたいな書き方はできないよ！

2017-02-08 01:49 UTC, nekoze1210 commented on app/controllers/chats_controller.rb
> +        format.json { render json: chat }
このchatは何ぞ？
あと、Railsのレコードをjsonに変換してあげよう

2017-02-08 08:09 UTC, ta910 commented on app/assets/javascripts/chat.js
> +    var html = '<li class="chat">' + '<div class="chat_content">' + '<h3>' + chat.user.name + '</h3>' + '<h5>' + chat.created_at + '</h5>' + '<h4>' + chat.body + '</h4>' + '</div>' + '</li>'
はい！

2017-02-08 08:09 UTC, ta910 commented on app/controllers/chats_controller.rb
> +        format.json { render json: chat }
変換しました！

2017-02-08 08:09 UTC, ta910 commented
turbolinks直せました！！ただデータを送るときにエラーが起きているようです、、、

2017-02-08 15:51 UTC, nkz-d reviewed
細かい点修正したらLGTMで！

2017-02-08 15:51 UTC, nekoze1210 commented on app/assets/javascripts/chat.js
> +    var html = '<li class="chat">' + '<div class="chat_content">' + '<h3>' + chat.name + '</h3>' + '<h5>' + chat.time + '</h5>' + '<h4>' + chat.body + '</h4>' + '</div>' + '</li>'
ここ見づらいから改行とかでHTMLっぽくしたほうが良さそう！

2017-02-08 15:51 UTC, nekoze1210 commented on app/assets/javascripts/chat.js
> +      $('form')[0].reset();
$('form')→chatにしたほうがいいね！

2017-02-08 15:56 UTC, merged