S3の導入
ta910/chat-space pull request #17
Opened 2017-02-14 21:40 UTC by ta910

# What
S3の導入
# Why
画像のアップロード先を変えるため

2017-02-14 21:41 UTC, ta910 commented
https://gyazo.com/443c982b4057d7cf2e96673a45559606

2017-02-14 21:42 UTC, ta910 commented
画像を送るとエラー起きるようになりました、、キーはあってると思うのですが、、

2017-02-15 14:48 UTC, nekoze1210 commented
AWSのアクセスキーが無効ですみたいなメッセージ書いてあるけど実際どうなんだ？ｗ…

2017-02-15 14:50 UTC, nkz-d requested changes

2017-02-15 14:50 UTC, nekoze1210 commented on app/uploaders/image_uploader.rb
> +  storage :fog
環境毎にアップロードするstorageの設定を分けてあげよう

2017-02-15 14:56 UTC, nekoze1210 commented on config/initializers/carrierwave.rb
> +      config.asset_host = 's3user--backet.s3-website-ap-northeast-1.amazonaws.com/s3user--backet'
ホストって確かhttp://~~から始まらなかったっけ？💦

2017-02-28 15:56 UTC, nkz-d commented
LGTM!

2017-02-28 18:51 UTC, merged